<?php
/**
 * Listing of articles in archive
 *
 * @var $paginator Zend\Paginator\Paginator
 */

$this->headLink()->appendAlternate($this->url('/feed'), 'application/rss+xml', 'RSS Feed');
$this->headTitle()->append('Blog Archive');

if ($paginator) {
    $this->headTitle()->append('Page ' . $paginator->getCurrentPageNumber());
};
?>

<?php if (count($this->paginator)): ?>
<div class="row">
<?php foreach ($this->paginator as $article): ?>
    <div class="large-6 columns margin-3">
         <?= $this->render('soflomo-blog/article/listing')?>
    </div>
<?php endforeach; ?>
</div>

<div class="row">
    <div class="large-6 columns">
        <div class="blog-pagination">
        <?= $this->paginationControl($this->paginator, 'Sliding',
                                     'soflomo-blog/pagination/control', array('route' => '/archive')); ?>
        </div>
    </div>
</div>
<?php endif; ?>