<?php
/**
 * Listing of articles by date
 *
 * @var $articles Array or recent articles
 * @var $from     DateTime
 * @var $to       DateTime
 */
?>
<h1>Blog</h1>

<?php foreach ($articles as $article):?>
    <article>
        <h2><a href="<?php echo $this->url('/view', array(
            'article' => $article->getId(),
            'slug'    => $this->slug($article->getTitle()),
        ))?>">
            <?php echo $this->escapeHtml($article->getTitle())?>
        </a></h2>
        <p><?php echo $article->getLead()?></p>
    </article>
<?php endforeach ?>