<?php
/**
 * Listing of recent articles
 *
 * @var $articles Array or recent articles
 */
$this->headLink()->appendAlternate($this->url('/feed'), 'application/rss+xml', 'RSS Feed');
?>

<div class="row">
    <div class="large-6 columns margin-3">
        <?= $this->render('soflomo-blog/article/listing', array('articles' => $left))?>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <a class="blog-pagination" href="<?= $this->url('/archive', array('page' => 2))?>"><?= $this->translate("More posts")?> &#x203A;</a>
    </div>
</div>