<?php
/**
 * Listing of recent articles
 *
 * @var $articles Array or recent articles
 */
?>
<h1>Blog</h1>

<?php foreach ($articles as $article):?>
    <article>
        <h2><a href="<?php echo $this->url('blog/view', array('article' => $article->getId()))?>">
            <?php echo $this->escapeHtml($article->getTitle())?>
        </a></h2>
        <p><?php echo $this->escapeHtml($article->getLead())?></p>
    </article>
<?php endforeach ?>