<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Soflomo\Blog\Module'                       => __DIR__ . '/Module.php',
    'Soflomo\Blog\Repository\Article'           => __DIR__ . '/src/Soflomo/Blog/Repository/Article.php',
    'Soflomo\Blog\Options\ModuleOptions'        => __DIR__ . '/src/Soflomo/Blog/Options/ModuleOptions.php',
    'Soflomo\Blog\Controller\ArticleController' => __DIR__ . '/src/Soflomo/Blog/Controller/ArticleController.php',
    'Soflomo\Blog\Entity\ArticleInterface'      => __DIR__ . '/src/Soflomo/Blog/Entity/ArticleInterface.php',
    'Soflomo\Blog\Entity\Article'               => __DIR__ . '/src/Soflomo/Blog/Entity/Article.php',
    'Soflomo\Blog\Entity\Category'              => __DIR__ . '/src/Soflomo/Blog/Entity/Category.php',
    'Soflomo\Blog\Entity\Blog'                  => __DIR__ . '/src/Soflomo/Blog/Entity/Blog.php',
    'Soflomo\Blog\Entity\BlogInterface'         => __DIR__ . '/src/Soflomo/Blog/Entity/BlogInterface.php',
    'Soflomo\Blog\Entity\CategoryInterface'     => __DIR__ . '/src/Soflomo/Blog/Entity/CategoryInterface.php',
);