<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Soflomo\Blog\Module'                               => __DIR__ . '/Module.php',
    'Soflomo\Blog\Repository\Article'                   => __DIR__ . '/src/Soflomo/Blog/Repository/Article.php',
    'Soflomo\Blog\View\Helper\Slug'                     => __DIR__ . '/src/Soflomo/Blog/View/Helper/Slug.php',
    'Soflomo\Blog\Exception\ArticleNotFoundException'   => __DIR__ . '/src/Soflomo/Blog/Exception/ArticleNotFoundException.php',
    'Soflomo\Blog\Exception\BlogNotFoundException'      => __DIR__ . '/src/Soflomo/Blog/Exception/BlogNotFoundException.php',
    'Soflomo\Blog\Exception\InvalidArgumentException'   => __DIR__ . '/src/Soflomo/Blog/Exception/InvalidArgumentException.php',
    'Soflomo\Blog\Options\ModuleOptions'                => __DIR__ . '/src/Soflomo/Blog/Options/ModuleOptions.php',
    'Soflomo\Blog\Controller\ArticleController'         => __DIR__ . '/src/Soflomo/Blog/Controller/ArticleController.php',
    'Soflomo\Blog\Controller\FeedController'            => __DIR__ . '/src/Soflomo/Blog/Controller/FeedController.php',
    'Soflomo\Blog\Entity\ArticleInterface'              => __DIR__ . '/src/Soflomo/Blog/Entity/ArticleInterface.php',
    'Soflomo\Blog\Entity\BlogBase'                      => __DIR__ . '/src/Soflomo/Blog/Entity/BlogBase.php',
    'Soflomo\Blog\Entity\Article'                       => __DIR__ . '/src/Soflomo/Blog/Entity/Article.php',
    'Soflomo\Blog\Entity\ArticleBase'                   => __DIR__ . '/src/Soflomo/Blog/Entity/ArticleBase.php',
    'Soflomo\Blog\Entity\Blog'                          => __DIR__ . '/src/Soflomo/Blog/Entity/Blog.php',
    'Soflomo\Blog\Entity\BlogInterface'                 => __DIR__ . '/src/Soflomo/Blog/Entity/BlogInterface.php',
    'Soflomo\BlogAdmin\Service\Article'                 => __DIR__ . '/src/Soflomo/BlogAdmin/Service/Article.php',
    'Soflomo\BlogAdmin\Form\Article'                    => __DIR__ . '/src/Soflomo/BlogAdmin/Form/Article.php',
    'Soflomo\BlogAdmin\Controller\ArticleController'    => __DIR__ . '/src/Soflomo/BlogAdmin/Controller/ArticleController.php',
    'SoflomoTest\Blog\Repository\ArticleRepositoryTest' => __DIR__ . '/tests/SoflomoTest/Blog/Repository/ArticleRepositoryTest.php',
    'SoflomoTest\Blog\Controller\ArticleControllerTest' => __DIR__ . '/tests/SoflomoTest/Blog/Controller/ArticleControllerTest.php',
);