<?php
/**
 * Create page of blog article in admin
 *
 * @var $blog    Current blog
 * @var $form    Form to edit article
 */
?>

<h1>New article</h1>

<?php $form->prepare()?>
<?php echo $this->form()->openTag($form)?>
    <?php echo $this->formRow($form->get('title'))?>
    <?php echo $this->formRow($form->get('lead')->setAttributes(array(
        'cols' => 50,
        'rows' => 10,
    )))?>
    <?php echo $this->formRow($form->get('body')->setAttributes(array(
        'cols' => 50,
        'rows' => 10,
    )))?>
    <?php echo $this->formRow($form->get('publish_date')) ?>
    <button type="submit">Save</button>
<?php echo $this->form()->closeTag()?>