<?php
/**
 * Listing of blog articles in admin
 *
 * @var $blog        Current blog
 * @var $paginator   Articles from this blog
 * @var $unpublished Unpublished articles from this blog
 */
?>

<h1>Blog listing</h1>

<a href="<?php echo $this->url('zfcadmin/blog/article/create', array(),array(),true)?>">
    New article
</a>

<a href="<?php echo $this->url('zfcadmin/blog/category', array(), array(), true)?>">Categories</a>

<?php if (count($this->unpublished)): ?>
<ul>
<?php foreach ($this->unpublished as $article): ?>
    <li><a href="<?php echo $this->url('zfcadmin/blog/article/view', array(
        'article' => $article->getId(),
    ), array(), true)?>">
        <?php echo $this->escapeHtml($article->getTitle())?>
    </a></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php if (count($this->paginator)): ?>
<ul>
<?php foreach ($this->paginator as $article): ?>
    <li><a href="<?php echo $this->url('zfcadmin/blog/article/view', array(
        'article' => $article->getId(),
    ), array(), true)?>">
        <?php echo $this->escapeHtml($article->getTitle())?>
    </a></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'soflomo-blog-admin/pagination/control', array('route' => 'zfcadmin/blog', 'slug' => $blog->getSlug())); ?>