<?php
/**
 * Edit page of blog article in admin
 *
 * @var $blog    Current blog
 * @var $article Article from this blog
 * @var $form    Form to edit article
 */

use IntlDateFormatter as Format;
$this->plugin('translate')->setTranslatorTextDomain('blog');
?>

<div class="page-header">
    <h1><?= $this->translate("Edit article")?></h1>
    <a href="<?php echo $this->url('zfcadmin/blog', array('blog' => $blog->getSlug()))?>">&larr; <?= $this->translate("Article overview")?></a>
</div>

<ul class="nav nav-pills">
    <li class="active"><a href="<?php echo $this->url('zfcadmin/blog/article/update', array(),array(),true)?>"><?= $this->translate("Edit article")?></a></li>
    <li><a href="<?php echo $this->url('zfcadmin/blog/article/view', array(),array(),true)?>"><?= $this->translate("Preview")?></a></li>
</ul>

<div class="row-fluid">
    <div class="editor blog-container">
        <?= $this->render('soflomo-blog-admin/article/form')?>
    </div>
</div>