<?php
/**
 * (Pre)view page of blog article in admin
 *
 * @var $blog    Current blog
 * @var $article Article from this blog
 */

use IntlDateFormatter as Format;
$this->plugin('translate')->setTranslatorTextDomain('blog');
?>

<div class="page-header">
    <h1><?= $this->translate("Preview article")?></h1>
    <a href="<?php echo $this->url('zfcadmin/blog', array('blog' => $blog->getSlug()))?>">&larr; <?= $this->translate("Article overview")?></a>
</div>

<ul class="nav nav-pills">
    <li><a href="<?php echo $this->url('zfcadmin/blog/article/update', array(),array(),true)?>"><?= $this->translate("Edit article")?></a></li>
    <li class="active"><a href="#"><?= $this->translate("Preview")?></a></li>
</ul>

<div class="row-fluid">
<article class="blog-container">
    <h1><?php echo $this->escapeHtml($article->getTitle())?></h1>

    <?php echo $article->getLead()?>
    <?php echo $article->getBody()?>

</article>
</div>