<?php
/**
 * (Pre)view page of blog article in admin
 *
 * @var $blog    Current blog
 * @var $article Article from this blog
 */
?>

<ul>
    <li><a href="<?php echo $this->url('zfcadmin/blog', array('blog' => $blog->getSlug()))?>">Back to listing</a></li>
    <li><a href="<?php echo $this->url('zfcadmin/blog/article/update', array(),array(),true)?>">Edit this article</a></li>
</ul>

<article>
    <h1><?php echo $this->escapeHtml($article->getTitle())?></h1>
    <p><?php echo $article->getLead()?></p>
    <p><?php echo $article->getBody()?></p>
</article>