<?/*
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
*/?>

<?php if ($this->pageCount): ?>
<div class="pagination">
<ul>
<?/* Previous page link */?>
<?php if (isset($this->previous)): ?>
  <li>
    <a href="<?php echo $this->url($this->route, array('page' => $this->previous, 'blog' => $this->slug)); ?>">&lt; <?= $this->translate("Previous")?></a>
  </li>
<?php else: ?>
  <li class="disabled"><span>&lt; <?= $this->translate("Previous")?></span></li>
<?php endif; ?>

<?/* Numbered page links */?>
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <li>
        <a href="<?php echo $this->url($this->route, array('page' => $page, 'blog' => $this->slug)); ?>">
            <?php echo $page; ?>
        </a>
    </li>
  <?php else: ?>
    <li class="active">
        <span><?php echo $page; ?></span>
    </li>
  <?php endif; ?>
<?php endforeach; ?>

<?/* Next page link */?>
<?php if (isset($this->next)): ?>
  <li>
    <a href="<?php echo $this->url($this->route, array('page' => $this->next, 'blog' => $this->slug)); ?>"><?= $this->translate("Next")?> &gt;</a>
  </li>
<?php else: ?>
  <li class="disabled"><span><?= $this->translate("Next")?> &gt;</span></li>
<?php endif; ?>
</ul>
</div>
<?php endif; ?>